### ISSUE TITLE
Learn the basics of Unity

### ISSUE THREAD

**Issue by rileycleavenger** [Andrew-Kohler/Daredevil64#2]
Learn the essentials of Unity and C#

**Comment by Andrew-Kohler** [comment]
https://www.youtube.com/playlist?list=PLrnPJCHvNZuB5ATsJZLKX3AW4V9XaIV9b Here’s the tutorial I was recommending - you’ll probably be able to speed it up a little/click through some of the longer vids, but it’s a good start for a whole bunch of Unity stuff. Don’t worry that it’s 3D - at the level we’ll be working at, there are very few differences between 3D and 2D.
