### ISSUE TITLE
Think of a better name

### ISSUE THREAD

**Issue by rileycleavenger** [Andrew-Kohler/Daredevil64#6]
Think of a better name for the game than "Echo Exploration"

**Comment by Andrew-Kohler** [comment]
Something to do with the ocean/the sea? I can’t stop thinking about the wave association, and it wouldn't be a bad fit for the sort of dreamy tone

**Comment by Andrew-Kohler** [comment]
So, going off of the theme of this being sort of an immersive audioscape:
- Ripples (a drop in a pond sending waves outward that set off a chain reaction, pretty relevant)
- Pondland (same idea, just sillier execution)
- The Mundane Sea (plays on the idea of sound playing a larger role in life than most people realize - an oxymoron of a title, as no sea is mundane)

Not really in love with any of them right now, but there's some to start. Just thinking about it, a sea theme for a level where there are, like, dolphins and fish swimming by through the air, and kelp and grasses waving in the background would be really cool and dream-like, though.

**Comment by Andrew-Kohler** [comment]
- Wavewalker? 
- Echovocation? Echosensation? Sort of forks of the original title

**Comment by Andrew-Kohler** [comment]
Also, this is just a side note, but I can't stop thinking about a carnival level where you go around to flip switches and turn the ferris wheel on and then ride to the top of the ferris wheel - carnivals have lots of cool and distinct noises and atmosphere

**Comment by Jodiiiiiiii** [comment]
theming some of the worldbuilding stuff around an absurd void occasionally filled with carnival items (hot dog stand, Ferris Wheel, cotton candy) sounds silly to me. Could give some more direction for a title as well

**Comment by Andrew-Kohler** [comment]
Come one, come all
    To our wonderland of glee
         Come one, come all, to **The Echoic Reverie!**

**Comment by Jodiiiiiiii** [comment]
The Echoic Reverie accepted
