### ISSUE TITLE
Develop Two Sample Puzzle Mechanics within a Level

### ISSUE THREAD

**Issue by rileycleavenger** [Andrew-Kohler/Daredevil64#9]
- one mechanic is based on movement
- one mechanic is based on interactions with enemies (@Andrew-Kohler has enemy designs we can use)

**Comment by Andrew-Kohler** [comment]
![image](https://github.com/rileycleavenger/Daredevil64/assets/32870812/b525fae6-dd98-41a6-9d19-bdf60eaa027e)

**Comment by Andrew-Kohler** [comment]
![image](https://github.com/rileycleavenger/Daredevil64/assets/32870812/40c67f17-1cdd-4fc9-823e-de9192500e09)

**Comment by TylerMetz** [comment]
Cascading sound effect setting each other off to solve a puzzle.

**Comment by Jodiiiiiiii** [comment]
Levels designed and created
